### PR TITLE
add new structs and methods for Bot API 5.1

### PR DESCRIPTION
**Pull request by snaffi**
* ChatMemberUpdated
* VoiceChatStarted
* VoiceChatEnded
* VoiceChatParticipantsInvited
* MessageAutoDeleteTimerChanged
* ChatInviteLink

new permissions

* CanManageVoiceChats
* CanManageChat

new methods

* CreateChatInviteLink
* EditChatInviteLink
* RevokeChatInviteLink

### CODE REVIEW

**Comment by snaffi** [comment]
@Syfaro @tjhorner FYI

**Comment by hanagantig** [comment]
Hi. My pull request is waiting for a comment about 5 month)

https://github.com/go-telegram-bot-api/telegram-bot-api/pull/408

**Comment by and3rson** [comment]
Is this project still alive? @Syfaro @tjhorner

I'm the author of github.com/and3rson/telemux library which heavily depends on your lib and am really worried about the state of this project.

**Comment by Syfaro** [comment]
@and3rson yes, this is still maintained. It's a bit of a mess right now, because all of the recent changes are only on the [develop](https://github.com/go-telegram-bot-api/telegram-bot-api/tree/develop) branch (because of breaking changes). I wish I could change the default branch GitHub shows without changing the default branch Git clones. 

A lot of the open PRs and issues are related to adding features that already exist on that branch and I haven't had the time to go through and explain that.

**Comment by Syfaro** [comment]
Hi, thanks for the PR! These changes were already made in the develop branch, which has now finally been merged into master.

**Pull request closed without merging**
