### PR TITLE
Update go module for the last tag - v5

### PR DESCRIPTION
**Pull request by romanitalian**
Actualize go module for the last tag: v5.0.1
Issue: "v5.0.1 misses go mod version #407"

### CODE REVIEW

**Comment by romanitalian** [comment]
@Syfaro please merge this PR to master.
Thank you for your attention and for this repository.

**Comment by and3rson** [comment]
@Syfaro bumping this just in case you've missed this. Thanks!

**Comment by andig** [comment]
ping @Syfaro please merge- this is the Go standard

**Comment by Syfaro** [comment]
Hi, sorry for the delay in reviewing PRs. 

The master branch is currently v4, the develop branch where v5 lives is set to v5.

https://github.com/go-telegram-bot-api/telegram-bot-api/blob/000cb2eb0eed1de00a3c4a90d2fc085abb7040c6/go.mod#L1

**Comment by andig** [comment]
The master branch is missing the v4 afaikt https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/go.mod#L1

**Comment by Syfaro** [comment]
It is, because v4 predates Go's module system and adding it would be a breaking change.

I still highly encourage everyone to be using v5@develop for now, because it's the only way to get a lot of features. I'd like to tag a new v5 release soon, but there's still a few other things to get out of the way first.

**Comment by Syfaro** [comment]
Version with v5 has been merged to master, with a new release soon.

**Pull request closed without merging**
