### PR TITLE
Added support for a Live Location methods (bot API 3.4)

### PR DESCRIPTION
**Pull request by pr0head**

### CODE REVIEW

**Comment by pr0head** [comment]
Tests is failed becouse current version `github.com/go-telegram-bot-api/telegram-bot-api` not have param `live_period` in `NewLocation` func.
What is the best practice for such a case?

**Comment by zhuharev** [comment]
@pr0head We can not refuse backward compatibility, it is better to make a new helper like a `NewLocationWithLivePeriod` or make livePeriod optional changing the
```go
func NewLocation(chatID int64, latitude float64, longitude float64, live_period int) LocationConfig {
...
```
to
```go
func NewLocation(chatID int64, latitude float64, longitude float64, livePeriods ...int) LocationConfig {
var (
  livePeriod = 0
)
if len(livePeriods) > 0 {
  livePeriod = livePeriods[0]
}
```

And please, use camelCase for variables.

**Comment by 5hanth** [comment]
@zhuharev any idea when we can have this on master?

**Comment by Syfaro** [comment]
This was merged into the develop branch and fixed for backwards compatibility.

**Pull request closed without merging**
