### PR TITLE
EditMessageMedia - Added Edit using Upload

### PR DESCRIPTION
**Pull request by aliforever**
Edit Message Media Added

### CODE REVIEW

**Comment by zhuharev** [comment]
@aliforever resolve conflict please

**Comment by aliforever** [comment]
Done @zhuharev

**Comment by zhuharev** [comment]
> Done @zhuharev

check ci something is wrong

**Comment by zhuharev** [comment]
@aliforever ping

**Comment by aliforever** [comment]
@zhuharev sorry, I guess it's alright now

**Comment by aliforever** [comment]
Right, I've just added uploading new files

**Comment by Defman21** [comment]
Any progress on that?

**Comment by DarkDrim** [comment]
Will this PR merged?

**Comment by Syfaro** [comment]
Closing in favor of #356

**Pull request closed without merging**
