### PR TITLE
Add DeleteMessage function

### PR DESCRIPTION
**Pull request by mamal72**
📚 [Docs](https://core.telegram.org/bots/api#deletemessage)

### CODE REVIEW

**Comment by Syfaro** [comment]
Hm, I'm a bit conflicted about this one. All the other functions don't operate on an actual `Message` type, they work on a `Config` type with only the relevant fields for the method. However being able to pass a `Message` makes a lot of sense. I'm not sure if using an `interface{}` instead would be better, or if there should be a second function.

**Comment by mamal72** [comment]
Hm... So your suggestion is to have some config struct type named `DeleteChatConfig` and use it for delete message method?

**Comment by Syfaro** [comment]
Well, `DeleteMessageConfig`, but yes. That way it's consistent with every other method.

**Comment by mamal72** [comment]
Closing in favor of #100.

**Pull request closed without merging**
