### PR TITLE
 Close update channel and cancel current request on shutdown

### PR DESCRIPTION
**Pull request by AstolfoKawaii**
Something similar to #218 but with aim to be able exit loops like for update := range updates

(re-implementation of #284)

### CODE REVIEW

**Comment by AstolfoKawaii** [comment]
There are two solutions of `./bot.go:88:14: undefined: http.NewRequestWithContext` the first one is to drop support of go <= 1.12 (current is 14), the second is to use different approach of adding context. Which solution do you prefer?

**Comment by AstolfoKawaii** [comment]
Rebased on updated master with fixed CI

**Comment by tjhorner** [comment]
>the first one is to drop support of go <= 1.12 (current is 14)

Since this library doesn't have any real versioning at the moment, this would be pretty undesirable since it has a high chance of breaking existing installs. @Syfaro what do you think?

**Comment by AstolfoKawaii** [comment]
> Since this library doesn't have any real versioning at the moment, this would be pretty undesirable since it has a high chance of breaking existing installs. @Syfaro what do you think?

He (or she, I am not sure) has already done so. (https://github.com/go-telegram-bot-api/telegram-bot-api/commit/dff2120d96a3baa18c2a73b5fc56fb744ad04665)

**Comment by Syfaro** [comment]
I merged these changes into #456.

**Pull request closed without merging**
