### PR TITLE
GO VERSION: update to 1.15

### PR DESCRIPTION
**Pull request by romanitalian**
In current date (2021-02-13) last stable golang version: 1.15.
And for this reason - update go version in go.mod.

### CODE REVIEW

**Comment by romanitalian** [comment]
@Syfaro please merge this PR to master.
Thank you for your attention and for this repository.

**Comment by zhuharev** [comment]
@romanitalian аre there any other reasons to remove support for older versions?

**Comment by Syfaro** [comment]
As far as I can tell, there's not really any reason to change this? It doesn't seem to change anything either way. Please correct me if I'm wrong.

**Comment by Syfaro** [comment]
It's now been bumped to Go 1.16.

**Pull request closed without merging**
