### PR TITLE
Fix nil pointer dereference in bot_test.go

### PR DESCRIPTION
**Pull request by ErrorBoi**
Fixed nil pointer dereference in bot_test.go, which is described in [this issue](https://github.com/go-telegram-bot-api/telegram-bot-api/issues/311)

### CODE REVIEW

**Comment by kortov** [comment]
@ErrorBoi thanks for PR. Honestly I'm nearly zero in go, but I think just returning err in https://github.com/go-telegram-bot-api/telegram-bot-api/blob/aa124ef1e84ecc14654ad242f3cf3bd2b0d5956c/helpers.go#L394-L400
would be better. But I don't know if it breaks backward compatibility

**Comment by ErrorBoi** [comment]
@kortov yeah, returning error is usually better, but my idea was to make minimum changes in existing code

**Comment by Syfaro** [comment]
This is a clever way to avoid breaking backwards compatibility! It probably should be a breaking change though. If you want, you could update `NewWebhook` to return an error on the develop branch.

**Comment by Syfaro** [comment]
`NewWebhook` now returns an error.

**Pull request closed without merging**
