### PR TITLE
Update Readme with example for InlineKeyboard and CallbackQuery

### PR DESCRIPTION
**Pull request by BigOokie**
Added a code example demonstrating usage of InlineKeyboard and CallbackQuery. The example was sourced from the [GoLang Telegram Bot API Telegram chat](https://t.me/go_telegram_bot_api), and was contributed by the user `@trigun117` (Vadim).

This is not my original work, but was extremely useful in better understanding the usage of InlineKeyboard and CallbackQuery

[Original source - Telegram Message](t.me/go_telegram_bot_api/9379)

### CODE REVIEW

**Comment by lukaszraczylo** [comment]
@BigOokie thank you so much, that's what I've been looking for and I really hope it'll get merged without issues.

**Comment by BigOokie** [comment]
NP - I was not the original author, but found it buried in the Telegram group. It solved my issue, so thought it would be worthwhile sharing.

**Comment by Syfaro** [comment]
Hi, sorry for the delay in review. I feel like the wiki is a more suitable location for examples instead of expanding the README. Adding too much code in the initial view of a project can be overwhelming. 

Alternatively, breaking examples into function specific parts and adding them into individual functions' documentation could be a good idea too. Perhaps even creating an example bot showing how to use all of the major functions would be a good idea too. 

Thank you for compiling this information though!

**Comment by BigOokie** [comment]
Agree - Wiki is a better place.

**Comment by Syfaro** [comment]
Yes, I absolutely agree including a link to the wiki is a good idea. I'm not sure how I overlooked that, especially with how GitHub doesn't make a distinction on projects that actually have wiki pages.

**Pull request closed without merging**
